### ISSUE TITLE
Scope / async issues

### ISSUE THREAD

**Issue by rexxars** [ibmruntimes/yieldable-json#8]
I'm not sure what the thinking is with [these variables](https://github.com/ibmruntimes/yieldable-json/blob/e19f4825e5bf5c17a2d73497d7d14f0774c42c52/yieldable-stringify.js#L17-L24) - they are shared between each invocation. Since this module is async, this isn't safe.

For instance, the check for circular references never resets between calls, and is not async safe. The following will claim that it encounters a circular reference on the second invocation, but not on the first:
```js
const yj = require('yieldable-json')

const child = {}
const obj = {child}

yj.stringifyAsync({obj}, (err, res) => {
  console.log(err, res)
  yj.stringifyAsync({obj}, (err, res) => {
    console.log(err, res)
  })
})
```

I would think that you could run into other, weird issues if you call `stringifyAsync` twice without chaining waiting for the first to complete

**Comment by gireeshpunathil** [comment]
thanks @rexxars - makes sense! I am tied up on bandwidth at the moment, but will look into it soon. PRs are welcome and much appreciated!

**Comment by logidelic** [comment]
Suggest that this is important enough to mention / warn about on the readme...

This library looks great and  implements something everybody in the node community wants. Thanks for the great work! However, it isn't ready for production use... Should be made explicit right up front...

**Comment by gireeshpunathil** [comment]
@logidelic - thanks for writing. why do you state that this isn't production ready yet? Is it due this reported issue, or due to some other reason? please elaborate.

**Comment by gireeshpunathil** [comment]
we are continuing to work on this issue, haven't been able to come up with a foolproof fix yet.

**Comment by logidelic** [comment]
@gireeshpunathil Yes, sorry for not being clear: I meant because of this issue. Specifically, the fact that it's not not "async safe" (which is a problem for an async library :) ).

Thanks again for all the efforts. If I have some free cycles I will certainly try to help out.

**Comment by gireeshpunathil** [comment]
@logidelic - thanks for the clarification. #15 is raised to address. Do you mind reviewing it and providing any feedback?
